[package]
name = "rust_python_integration"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "rust_python_integration"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.19.0"
rand = "0.9.0-alpha.0"
